### ISSUE TITLE
missing Plone 5 toolbar icons for fields and actions

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#16]
<img src=https://cloud.githubusercontent.com/assets/815418/11221929/538ef8a6-8d2d-11e5-9956-9ddabb741215.jpg>

**Comment by prakharjoshi** [comment]
@davilima6  What if we remove them from here as main toolbar and place these things in the standard Actions tab where we have other items related to easyforms too like `import`, `export`. This will help us in keeping the toolbar consistent too. Ideas ?

**Comment by davilima6** [comment]
I think that's the best move at the moment. Maybe you could rename the actions to "Define form fields" and "Define form actions" so the reading flows more naturally when user reads the Actions menu items. We just have to document (with screenshots) this since it will be much less visible at first sight than Plone 4's version.

In the near future we might create a new button (e.g. "Tools") to offer a place for add-on makers to register their custom views to. But that's not in your GSOC scope so I think your suggestion is the best right now.

**Comment by prakharjoshi** [comment]
@davilima6  Sure. I will rename the current `actions` and 'fields` with those types of names, It will be easy for users to differentiate between the main actions and the `action` items for easyforms and later we will plan something like to add a seperate item in main toolbar and we can place all these actions and sub items in the drop down of that item.

**Comment by prakharjoshi** [comment]
@davilima6  I guess we can close this, right with this fix [here](https://github.com/collective/collective.easyform/pull/31) ?

**Comment by davilima6** [comment]
Closed by #31
