### ISSUE TITLE
Do we need a modal pop up for settings of actions ?

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#27]
When we go to action listing http://localhost:8080/Plone/first-form/actions , there is a settings button for each action and it links to pop Up where we can configure the mailers or other actions. Like this :- 
![popup](https://cloud.githubusercontent.com/assets/6854139/15904477/e284483a-2dce-11e6-9d9f-8bf2a9926d39.png)

But we can directly link this settings to other page and we have that page too like for mailer we have ```http://localhost:8080/Plone/first-form/actions/mailer``` for editing mailer actions like this :- 
![mailer-edit](https://cloud.githubusercontent.com/assets/6854139/15904732/cbb3d2dc-2dcf-11e6-90e1-aaabb5fbb08b.png)

So why we need pop up for this when we already have a link for editing actions ? Is there something I am missing here ?

**Comment by davilima6** [comment]
I think it makes for a nicer UX, similarly to Content Rules.

**Comment by smcmahon** [comment]
Discussion on IRC leading to closing this item:

[10:22am] <SteveM>
_pjoshi: When you say “But we can directly link this settings to other page”, what’s the other page?
[10:22am]
andrea left the chat room. (Quit: I'm gonna save Rose Tyler from the middle of the Dalek fleet, and then I'm gonna save the Earth)
[10:23am] <_pjoshi>
SteveM:  Its like when we hit the settings we get the pop up, right? but http:://localhost:8080/Plone/first-form/actions/mailer(Other url) provides the same form that we get on pop up
[10:24am] <_pjoshi>
the form from which we can configure the mailer, or other actions
[10:24am] <SteveM>
_pjoshi: Nearly all the popup forms in Plone have full-page equivalents. But the popups are still convenient because they maintain context.
[10:25am] <_pjoshi>
SteveM:  Oh!! I never knew that 
[10:25am] <_pjoshi>
I though its a duplicate url
[10:25am] <SteveM>
Popups are generally handled by loading a part of the matching standalone page. The popup form is loaded via AJAX.
[10:26am] <_pjoshi>
Ah!! So its sort of improvement in terms of looks, right ?
[10:26am] <SteveM>
_pjoshi: User Interface. If you’ve got several actions to edit, it’s nice to stay on the page that lists the form actions.
[10:27am] <SteveM>
And just pop up the field editor.
[10:27am] <_pjoshi>
SteveM:  Ah!! Yeah your are right. Its more user friendly
[10:27am] <_pjoshi>
Cool!! Today I learnt new thing 
[10:28am] <SteveM>
It’s also a nice implementation because we give convenient UI, with a fall back if popups aren’t available.
[10:28am] <SteveM>
And we do it by implementing a page with a form and then using JS to load it as a popup when that helps the UI.
[10:28am] <SteveM>
A general pattern in Plone.
