### ISSUE TITLE
spinner keeps running after inline validation of a field

### ISSUE THREAD

**Issue by prakharjoshi** [collective/collective.easyform#5]
When I create a default form with the buildout included in the colective.easyform package from master (Plone 4.3-latest) , exiting a field when fillig in the form shows a spinner, but the spinner is never cancelled/hidden again.

Changing the fields (making them all not required, removing the email-validator from the default email field) doesn't make a difference.

<img src=https://cloud.githubusercontent.com/assets/394784/6039702/cec643e4-ac69-11e4-961a-89fe5c8fcf76.gif>

This issue is raised by @fredvd .

**Comment by agitator** [comment]
Didn't notice that within Plone 5. Since we target Plone 5, please reopen if still an issue.

**Comment by fredvd** [comment]
@agitator There is an 1.X branch of collective.easyform which is in use on Production Plone 4 sites, at least we have a few still in support. 

Closing issues because you target Plone 5 in 2.x Is not enough reason to close tickets where Plone 4 is mentionned ;-)

This seems to be related to #59 , the inline validation which was fixed by https://github.com/collective/collective.easyform/commit/64f09d8ccc750f1199e1799c44dceea04fc8d066 . I'll see if I can backport this to 1.x

**Comment by agitator** [comment]
@fredvd valid point, a pull request is always welcome ;-)

**Comment by fredvd** [comment]
Fixed in 1.x and master, inline validation was missing but has been restored.
