### ISSUE TITLE
ImportError: No module named validation

### ISSUE THREAD

**Issue by agitator** [collective/collective.easyform#80]
Happens in an archetypes-free Plone 5.1b4-pending instance

- Products.validation is missing without Archetypes as dependency
- Products.validation says "Data validation package for Archetypes."
- is "Products.validation" only for Archetypes?
- if not, the package description should be changed and added as a dependendy for easyforms
- or?

@tomgross what's your opinion?

**Comment by agitator** [comment]
@mauritsvanrees is Products.validation meant to be Archetypes specific?

**Comment by tomgross** [comment]
@agitator The only AT dependency of Products.validation is for tests. More explicitly in https://github.com/plone/Products.validation/blob/master/Products/validation/tests/test_validation.py#L3
It should be trivial to port this to plone.app.testing or even Zope only tests (with porting to Py3 in mind ;-))

**Comment by agitator** [comment]
Maybe my explanation wasn't good enough...
- Products.validation isn't a dependency of easynewsletter now and therefore I got that error
- So it should be a dependendy of easyforms?

**Comment by mauritsvanrees** [comment]
I am pretty sure `Products.validation` is only needed for Archetypes. Since easyform uses dexterity, it seems strange that this package would be needed. I haven't dived into easyform, but I expect that all forms use `z3c.form`, so validation would be done using standard `z3c.form` methods. My guess is that easyform should be changed to not need `Products.validation`. But I have not looked at the code.

Fastest way forward may be to temporarily add it as a dependency of easyform anyway, because that fits the current situation.

**Comment by tomgross** [comment]
`Products.validation` might only be used by Archetypes but does not have any Archetype dependencies itself. Here is a PR for a version with the unnecessary testing dependencies removed: https://github.com/plone/Products.validation/pull/3

**Comment by agitator** [comment]
Products.validation is used in https://github.com/collective/collective.easyform/blob/master/src/collective/easyform/validators.py#L66

**Comment by agitator** [comment]
https://github.com/collective/collective.easyform/pull/85

**Comment by blue1master1** [comment]
ModuleNotFoundError: No module named 'validation'

**Comment by mauritsvanrees** [comment]
Details?
