### ISSUE TITLE
Improve file handling in forms

### ISSUE THREAD

**Issue by tomgross** [collective/collective.easyform#92]
collective.easyform (2.0.0b2 - master)

1. If you upload a file to a form the information on the thanks page is misleading:

![grafik](https://user-images.githubusercontent.com/339384/30321032-e9ff149a-97b4-11e7-8d86-bfb163593f51.png)

The Size and Mime-Type should be removed because size is always 0KB and the Mime-Type is too technical for most users.

2. If you have a file upload in a form and the form does not submit because of a validation error a misleading choice is shown (This makes sense for persistent content but not for forms). There is no file to keep at this place. A validation error should be issued at this place to inform the user to upload the file again.

![grafik](https://user-images.githubusercontent.com/339384/30321207-8e749392-97b5-11e7-92ab-fd2ebafe02da.png)

**Comment by thet** [comment]
The second problem also appears for standard Dexterity Add-forms.

**Comment by thet** [comment]
after submitting and getting this error for add forms, we cannot keep the file even though it was already uploaded and is (under linux) in /tmp.
keeping would mean adding the the path to the file to the form which will be resubmitted. that would open up a severe security issue, because any file could be referenced.
